// The challenges this server has issued and not yet spent.
//
// WHY THERE IS NO TABLE FOR THIS. The frozen schema has two tables, and a challenge is in neither.
// That is the right shape rather than an omission to work around: a challenge lives for one
// ceremony, is spent the moment it is answered, and has no meaning to anything else in the app. A
// row per issued challenge on an UNAUTHENTICATED endpoint is also a write anybody can cause, which
// is a different and worse problem than the one it solves.
//
// WHAT THIS IS: a bounded, in-process set with a short TTL, spent on read. What it costs, stated
// rather than discovered:
//
//   * A RESTART FORGETS OUTSTANDING CHALLENGES. A ceremony in flight across a restart fails and the
//     owner clicks again. That is the whole consequence, and it fails CLOSED — a forgotten
//     challenge is refused, never accepted.
//   * IT IS PER-PROCESS. `next start` runs one process; if this app is ever run behind more than
//     one, a ceremony must complete against the instance that began it. Recorded here because the
//     day that changes, this file is what breaks, and it breaks by refusing logins rather than by
//     accepting them.
//
// WHY NOT A COOKIE, which is the obvious alternative and the one a quick-start reaches for: a
// challenge carried in a cookie is a challenge the CALLER supplies back, and a non-browser client
// sets whatever cookie it likes. The whole job of a challenge is to be a value the server chose for
// this attempt and no other, so putting it in the caller's hands makes a captured assertion
// replayable by anyone able to replay the cookie beside it. Server-side is the only place it means
// anything.
//
// HOW THIS IS USED AT THE VERIFY SITE, because it looks at first glance like the mistake it is
// specifically avoiding: `@simplewebauthn/server` accepts a PREDICATE for `expectedChallenge`, and
// the handlers pass `(challenge) => consumeChallenge(kind, challenge)`. The payload does not supply
// the expected value; it proposes one, and this store — the server's own, which an attacker cannot
// write to — answers whether the server issued it and had not yet spent it. A store holding nothing
// refuses everything, which is the behaviour on a cold start and the correct one.

import { createLogger } from './logger';

const log = createLogger('auth');

export type CeremonyKind = 'registration' | 'authentication';

/**
 * How long an issued challenge stays answerable.
 *
 * Five minutes: longer than any real ceremony (a Touch ID prompt is seconds) and short enough that
 * a challenge captured off the wire is useless by the time anybody gets to it. It is an upper
 * bound, not a schedule — the ordinary end of a challenge's life is being spent.
 */
export const CHALLENGE_TTL_MS = 5 * 60 * 1000;

/**
 * How many challenges may be outstanding per ceremony kind before the oldest is dropped.
 *
 * THIS IS NOT RATE LIMITING — that is step 13's job and an explicit non-goal here. It is a bound on
 * a data structure that an unauthenticated caller can cause writes to: `POST …/login/options`
 * answers anybody, so without a cap this Map grows for as long as somebody keeps asking. 64 is far
 * above any plausible number of ceremonies a single owner has in flight, so eviction is unreachable
 * in normal use; when it is reached, the oldest challenge is dropped, which refuses a ceremony
 * rather than admitting one.
 */
const MAX_OUTSTANDING = 64;

/** Issued challenge → the moment it stops being answerable. Keyed by kind so a registration
 *  challenge cannot be spent as an authentication one. */
const outstanding = new Map<string, number>();

function key(kind: CeremonyKind, challenge: string): string {
  return `${kind}:${challenge}`;
}

/** Drop everything past its TTL. Called on every write, so the map is pruned by use. */
function prune(now: number): void {
  for (const [entry, expiresAt] of outstanding) {
    if (expiresAt <= now) outstanding.delete(entry);
  }
}

/**
 * Record a challenge this server just issued.
 *
 * The challenge itself is generated by `@simplewebauthn/server`'s options builders, which use the
 * platform CSPRNG. It is not re-generated here: two sources of the same value is the defect this
 * repo opens its build document with.
 */
export function rememberChallenge(kind: CeremonyKind, challenge: string): void {
  const now = Date.now();
  prune(now);
  if (outstanding.size >= MAX_OUTSTANDING) {
    // Map iteration is insertion-ordered, so the first key is the oldest.
    const oldest = outstanding.keys().next();
    if (!oldest.done) {
      outstanding.delete(oldest.value);
      log.warn('outstanding challenge evicted', { kind, outstanding: outstanding.size });
    }
  }
  outstanding.set(key(kind, challenge), now + CHALLENGE_TTL_MS);
}

/**
 * Spend a challenge: true if this server issued it for this kind of ceremony and it is still live.
 *
 * SINGLE USE, and the deletion happens whether or not the challenge had expired — an answered
 * challenge is spent either way, so a caller cannot retry against the same value while it ages.
 */
export function consumeChallenge(kind: CeremonyKind, challenge: string): boolean {
  const entry = key(kind, challenge);
  const expiresAt = outstanding.get(entry);
  if (expiresAt === undefined) return false;
  outstanding.delete(entry);
  return expiresAt > Date.now();
}

/** How many challenges of a kind are outstanding. Diagnostics and fixtures only. */
export function outstandingChallenges(kind: CeremonyKind): number {
  prune(Date.now());
  return [...outstanding.keys()].filter((entry) => entry.startsWith(`${kind}:`)).length;
}
